
x-environment:
  DOCKER_BUILDKIT: "1"
services:
  # --- Сервис бота ---
  bot:
    build: .
    container_name: wincheckbot
    working_dir: /app
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./data:/app/data           # для SQLite-базы (pulse.db)
      - ./logs:/app/logs           # логи, если пишутся в файлы
      - ./import:/app/import       # папка для импортируемых файлов
      - ./export:/app/export       # папка для экспортируемых файлов
      - ./archive:/app/archive     # папка для архивных файлов
    command: ["python3", "main.py"]
    restart: unless-stopped

  # --- Сервис Redis ---
  redis:
    image: redis:7.4
    container_name: wincheckbot_redis
    command: ["redis-server", "--protected-mode", "no"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
