version: "3.9"

x-environment:
  DOCKER_BUILDKIT: "1"

services:
  # --- Сервис бота ---
  bot:
    build: .
    container_name: wincheckbot
    working_dir: /app
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./data:/app/data      # для SQLite (DB_PATH)
      - ./logs:/app/logs      # логи
      - ./import:/app/import
      - ./export:/app/export
      - ./archive:/app/archive
    # Команду бота берём из Dockerfile (CMD ["python3", "main.py"]), 
    # либо можно переопределить:
    command: ["python3", "main.py"]
    restart: unless-stopped

  # --- Сервис cron ---
  cron:
    build: .
    container_name: wincheckbot_cron
    working_dir: /app
    env_file:
    - .env
    volumes:
    - ./data:/app/data
    - ./logs:/app/logs
    - ./import:/app/import
    - ./export:/app/export
    - ./archive:/app/archive
    # Вместо "command: [\"cron\", \"-f\"]":
    command: ["/app/entrypoint-cron.sh"]
    restart: unless-stopped

  # --- Redis ---
  redis:
    image: redis:7.4
    container_name: wincheckbot_redis
    command: ["redis-server", "--protected-mode", "no"]
    volumes:
      - ./redis_data:/data
