version: "3.9"

services:
  bot:
    build: .
    container_name: wincheckbot
    working_dir: /app
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - ROLE=bot  # Указываем, что это бот
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./import:/app/import
      - ./export:/app/export
      - ./archive:/app/archive
    restart: unless-stopped

  cron:
    build: .
    container_name: wincheckbot_cron
    working_dir: /app
    env_file:
      - .env
    environment:
      - ROLE=cron  # Указываем, что это cron
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./import:/app/import
      - ./export:/app/export
      - ./archive:/app/archive
    restart: unless-stopped

  simulation:
    build: .
    container_name: wincheckbot_simulation
    working_dir: /app
    env_file:
      - .env
    environment:
      - ROLE=simulation  # Запускаем simulation.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./import:/app/import
      - ./export:/app/export
      - ./archive:/app/archive
    restart: unless-stopped
    
  redis:
    image: redis:7.4
    container_name: wincheckbot_redis
    command: ["redis-server", "--protected-mode", "no"]
    volumes:
      - ./redis_data:/data
